version: "3.2"
services:

  on-prem:
    image: stardog-stardog-apps.jfrog.io/cloud-login:onprem-current
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    for linux
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: stardog-apps
